### ISSUE TITLE
Any plans for unlinked references?

### ISSUE THREAD

**Issue by technovangelist** [jethrokuan/org-roam#240] opened 2020-03-06 14:31 UTC
### Brief Abstract
Unlinked references in addition to linked?

###Description
When I first saw roam one of the things that struck me as especially cool was the list of references on the right. You have the linked references but even more magical was the unlinked references. So if writing about kubernetes and a few notes include the command kubectl and kubectl is already a doc then even if I don’t link kubectl it’s listed in the unlinked references. How they have done it in roam  is amazing. 

Are there thoughts or plans for this in org roam?

**Comment by jethrokuan** [comment] 2020-03-06 14:58
Duplicate of #31 , there was an attempt at #170

**Closed by jethrokuan** 2020-03-06 14:58 UTC
Labels: enhancement
