### ISSUE TITLE
org-roam-find-file gives Invalid function helm-build-sync-source 

### ISSUE THREAD

**Issue by Xunius** [jethrokuan/org-roam#343] opened 2020-03-23 09:31 UTC
### Description

Running `M-x org-roam-find-file` with the variable `org-roam-completion-system` set to `'helm` gives the error `Invalid function helm-build-sync-source`.

#### Steps to Reproduce

1. Install and config `org-roam` as:

```
  (use-package org-roam
    :ensure t
    :hook
    (after-init . org-roam-mode)
    :custom
    (org-roam-directory "~/Notebooks/org/roam")
    :config
    (setq org-roam-completion-system 'helm)
    :bind
    (:map org-roam-mode-map
          (("C-c n l" . org-roam)
           ("C-c n f" . org-roam-find-file)
           ("C-c n b" . org-roam-switch-to-buffer)
           ("C-c n g" . org-roam-show-graph))
     :map org-mode-map
          (("C-c n i" . org-roam-insert))))
```

2. In Emacs, open an org file, activate `org-roam` by `C-c n l`.
3. Enable `helm-mode`
3. Run `M-x org-roam-find-file RET`

#### Expected Results

A list of existing files in the `org-roam-directory` should be displayed

#### Actual Results

The minibuffer shows `Invalid function helm-build-sync-source`.

### Fix worked for me

[This post](https://github.com/emacs-helm/helm/issues/602#issuecomment-54013408) suggests re-installing helm. But I found that I have to re-install `org-roam` for it to work. I guess it is required that `helm` should be installed before `org-roam`, but I have no idea. If so, maybe add a line somewhere in the doc specifying this?

- Emacs (`C-h v emacs-version`): vX.X.X
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/commithashhere

**Comment by jethrokuan** [comment] 2020-03-24 03:52
How did you install org-roam previously? It might've been the recent cleanup for MELPA that fixed it:

https://github.com/jethrokuan/org-roam/commit/07672213b6ce17017588f338a07ae17058348074#diff-0c901a6495bf5e72da2d3526eb3f6483R54

**Comment by Xunius** [comment] 2020-03-24 04:00
@jethrokuan I didn't manage to install org-roam manually previously, I saw the release notice yesterday so I tried the MELPA install, and I did it by

```
(use-package org-roam
    :ensure t
...
)
```
I was not using helm previously, I only installed helm because I'd like to have that nice full screen display of roam notes. So I installed org-roam, then helm.

**Comment by jethrokuan** [comment] 2020-03-24 04:13
>  I guess it is required that helm should be installed before org-roam

This is my guess now too, not sure.

**Comment by gambhiro** [comment] 2020-03-25 21:48
@jethrokuan What helm version are you using? How should one make sure it is loaded?

I tried `(setq org-roam-completion-system 'helm)` and I had the same error.

I removed helm and installed it, which didn't help. I removed org-roam and installed it (using a the github fetcher recipe). I tried to `(require 'helm)` before opening org-roam, but it still errors out when calling `org-roam-find-file`.

`helm-20200325.757`

`org-roam-20200324.422`

**Comment by gambhiro** [comment] 2020-03-28 07:51
I think the problem is in the order of byte compilation, when org-roam is installed automatically on emacs startup, helm is not yet loaded and helm-build-sync-source is missing at that moment.

This is what they are discussing here:

https://github.com/jacktasia/dumb-jump/issues/224

I am using this with spacemacs btw. Org-roam is loaded with a layer as recommended in the helpful docs on your site.

I saw #354 , removed org-roam, restarted emacs, which re-installed org-roam during startup. That didn't work, same problem.

Right after startup, the message is `Please install helm ...`. After opening and org file, the message is `Invalid function: helm-build-sync-source`.

The sequence below has got it working, the difference was that helm must be loaded when org-roam is installed and byte-complied.

- remove org-roam
- disable org-roam layer loading in `.spacemacs` (so that it is not auto-installed during startup)
- restart emacs
- open an org file (which loads helm)
- open paradox, install org-roam from melpa
- enable layer loading
- restart emacs
- `org-roam-find-file` right after startup: `Please install helm`
- open an org file
- find works with helm, no error

**Comment by brianmcgillion** [comment] 2020-03-29 13:04
In .doom.d/config.el I added the following to the `package! org-roam` stanza:
` :init
  (require 'helm)`

Then cleaned `.emacs.d/.local`. ran `.bin/doom upgrade`. and this appears to have byte-compiled in the correct order. i.e. org-roam-find-file is working again.

**Comment by gambhiro** [comment] 2020-03-29 16:14
@jethrokuan Brilliant, #375 fixed the compilation issue and adding `:init (require 'helm)` as @brianmcgillion suggested works when using `org-roam-find-file` right after emacs started.

**Comment by jethrokuan** [comment] 2020-03-29 18:35
Awesome! Closing as resolved

**Closed by jethrokuan** 2020-03-29 18:35 UTC
