### ISSUE TITLE
issue with `org-roam-completion--completing-read`

### ISSUE THREAD

**Issue by bdarcus** [jethrokuan/org-roam#514] opened 2020-04-23 18:55 UTC
@alan-carroll uncovered what was partially a bug in the Doom `org +roam` flag code, which resulted in not getting `ivy` fuzzy search in doom.

In the course of the discussion of how to fix it, @hlissner suggested the following [here](https://github.com/hlissner/doom-emacs/pull/2960#issuecomment-618581459).

> ... perhaps it would be better if org-roam-completion--completing-read didn't specify its own :re-builder? This overrides user customizations.

**Comment by alan-carroll** [comment] 2020-04-23 20:07
I think I can clarify some more now -- the use of 'fuzzy' has been leading to some confusion. I'm still learning emacs packages and how they apply terms!

The behavior I was expecting is ivy's default completion method `ivy--regex-plus`, where a space serves as a wildcard. With this method, searching 'b t' narrows the search to include 'bib_test', but 'bt' without the wildcard space does not. This is the default `find-file` behavior in Doom with ivy installed, but it was not working with `org-roam-find-file` or `org-roam-insert`.

Loading vanilla emacs gives the desired behavior with `M-x ivy-mode`, so I thought it might be something with Doom. However it appears it depends on `org-roam-completion-system`: in vanilla it loads as `default` because I was manually enabling `ivy-mode`, whereas in Doom it had been loading as `ivy`. In Doom, if I manually call `(setq org-roam-completion-system 'default)` then I get the expected behavior of ivy treating spaces as wildcards.

I will iterate through vanilla settings and behavior -- hopefully this is clear:
1. `ivy-mode`=t, `org-roam-completion-system`=default, `org-roam-completion-fuzzy-match`=nil
Default `ivy--regex-plus` behavior. Space is wildcard. 'b t' narrows to 'bib_test', while 'bt' excludes 'bib_test'.

2. `ivy-mode`=t, `org-roam-completion-system`=default, `org-roam-completion-fuzzy-match`=t
Exact same behavior as 1. 

3. `ivy-mode`=t, `org-roam-completion-system`=ivy, `org-roam-completion-fuzzy-match`=nil
Only tab-completion (I don't know what else to call this). 'b t' AND 'bt' excludes 'bib_test', but I can narrow with '_t'. So basically no fuzzy or wildcards

4. `ivy-mode`=t, `org-roam-completion-system`=ivy, `org-roam-completion-fuzzy-match`=t
This is `ivy--regex-fuzzy` behavior, I think? 'b t' excludes 'bib_test', while 'bt' includes it. So space is no longer wildcard.

5. `ivy-mode`=nil, `org-roam-completion-system`=default, `org-roam-completion-fuzzy-match`=t OR nil
Vanilla emacs search with completion on verbatim searches

6. `ivy-mode`=nil, `org-roam-completion-system`=ivy, `org-roam-completion-fuzzy-match`=nil
Ivy search (shows list of files that narrows as you type) but neither space wildcard or fuzzy. Both 'b t' and 'bt' exclude 'bib_test'

7. `ivy-mode`=nil, `org-roam-completion-system`=ivy, `org-roam-completion-fuzzy-match`=t
Same as 4, `ivy--regex-fuzzy`

So the only way I get spaces as wildcards following `ivy--regex-plus` method is with settings 1. or 2., when `org-roam-completion-system` is `default`, in both vanilla and doom emacs. In Doom the default configuration with +roam results in setting 3. above, resulting in neither wildcard OR fuzzy search with ivy (though helm appears to work as expected I think).

**Comment by alan-carroll** [comment] 2020-04-23 21:37
Yes I understand now. This is simple. The `org-roam-completion-fuzzy-match` conditional [in the :re-builder mentioned](https://github.com/jethrokuan/org-roam/blob/master/org-roam-completion.el#L86-L87) uses either `ivy--regex-fuzzy` if true or `regexp-quote` search method otherwise. I wanted `ivy--regex-plus`, which is what I normally get from ivy, and is what is used if `org-roam-completion-system` is set to default with ivy installed.

Doom had been setting `org-roam-completion-system` to `ivy` but leaving `org-roam-completion-fuzzy-match` as `nil`, meaning I was only getting `regexp-quote` searches in org-roam.

I've tested changing the :re-builder conditional from `regexp-quote` to `ivy--regex-plus`, or deleting it entirely, and both work as expected.

**Comment by bdarcus** [comment] 2020-04-23 21:48
So per the suggestion, the preferred solution is to delete that?

**Comment by alan-carroll** [comment] 2020-04-23 22:43
The Doom issue is a configuration one where `org-roam-completion-fuzzy-match` was not being set with ivy use -- [that is solved either with only setting default or hlissner's suggested conditional](https://github.com/hlissner/doom-emacs/pull/2960#issuecomment-618581459). I can otherwise get my desired functionality in any configuration simply by setting `org-roam-completion-system` to default.

The :re-builder in org-roam-completion is explicitly written, so I won't speculate if this is the intended functionality. It does what it is meant to do. @jethrokuan can clear that up!

**Comment by jethrokuan** [comment] 2020-04-25 11:16
wrt to `org-roam-completion-system`, these are for people to set if they wish to only use a certain completion system for the interactive commands. E.g. ivy enabled globally, but use helm for org-roam. In most cases, leaving it as the default would work as expected, so I think Doom can simply remove that `setq` invocation.

**Comment by hlissner** [comment] 2020-04-25 20:45
Should `org-roam-completion-fuzzy-match` exist at all? Should it be org-roam's responsibility to implement it at all? Neither the ido or default backends obey `org-roam-completion-fuzzy-match` (directly). Helm and ivy have their own mechanisms for enabling fuzzy search. Ido too, through the ido-flx plugin.

With `org-roam-completion--completing-read` hardcoding a :re-builder, we can't use any other re-builder besides `ivy--regex-fuzzy` and `regexp-quote`. i.e. this won't work :

```elisp
(add-to-list 'ivy-re-builders-alist '(org-roam--completing-read . ivy--regex-ignore-order))
;; Or replace `ivy--regex-ignore-order` with any backend
```

But this will, if `org-roam-completion-system` == `default`:

```elisp
(add-to-list 'ivy-re-builders-alist '(org-roam-capture . ivy--regex-ignore-order))
(add-to-list 'ivy-re-builders-alist '(org-roam-insert-file . ivy--regex-ignore-order))
```

But that seems roundabout.

**Comment by jethrokuan** [comment] 2020-04-26 09:28
> Should `org-roam-completion-fuzzy-match` exist at all?

Gotcha. I think this can be removed too.

**Comment by jethrokuan** [comment] 2020-04-28 06:14
Closing this with #523 merged.

**Closed by jethrokuan** 2020-04-28 06:14 UTC
