### ISSUE TITLE
org-roam-build-cache produce error "UNIQUE constraint failed: files.file"

### ISSUE THREAD

**Issue by BobCromwell** [jethrokuan/org-roam#522] opened 2020-04-26 03:06 UTC
#### Expected Results
No Error
#### Actual Results
peculiar error: "UNIQUE constraint failed: files.file"

### Versions
- Emacs (`C-h v emacs-version`): v"27.0.90"
- Org-roam commit: https://github.com/jethrokuan/org-roam/commit/963692f353090359b0513cc75abe92e7e7546bfc

**Comment by isolet** [comment] 2020-04-27 08:13
Same here.

**Comment by mindlike** [comment] 2020-04-29 18:25
Same here. I was able to fix this by deleting my `org-roam.db` file and rebuilding it with `org-roam-db-build-cache`.  

- GNU Emacs 28.0.50
- Org-roam commit: 4142300

**Comment by BobCromwell** [comment] 2020-04-30 02:48
I guess maybe org-roam does not handle .org_archive  file

**Comment by mindlike** [comment] 2020-04-30 04:49
I don't have any archive files in my org-roam directory.

**Comment by jethrokuan** [comment] 2020-04-30 05:48
I can't reproduce this on my end. Anyone here can give me a small set of files to reproduce this error?

**Comment by BobCromwell** [comment] 2020-04-30 09:53
> I can't reproduce this on my end. Anyone here can give me a small set of files to reproduce this error?

It seesm can't be reproduce any more using [7680663 ](https://github.com/jethrokuan/org-roam/commits/7680663)。Not quite sure why.

**Comment by jethrokuan** [comment] 2020-05-04 07:15
Closing for now, feel free to reopen when this is an issue.

**Closed by jethrokuan** 2020-05-04 07:15 UTC

**Comment by dangirsh** [comment] 2020-05-11 20:35
FYI, for me this went away after removing a symlink I had in my org-roam directory. It was pointing to a file outside of the org-roam directory (my .doom.d/config.org). That seemed to break an assumption in `org-roam-db-build-cache`.

If symlinks like that are unsupported, we should document that + warn users.

**Comment by jethrokuan** [comment] 2020-05-12 04:19
> If symlinks like that are unsupported, we should document that + warn users.

They should be supported: bug on our side.

**Comment by BobCromwell** [comment] 2020-05-26 03:05
Hit same error again using  https://github.com/org-roam/org-roam/commit/ea6bd215fc52c93460c7a96b7c0a0f97d3f5c8f3

**Comment by jethrokuan** [comment] 2020-05-26 06:29
@BobCromwell should be fixed by #700

**Comment by isolet** [comment] 2020-06-09 00:43
Same issue `Error running timer ‘require’: (emacsql-error "near line 2593: UNIQUE constraint failed: refs.ref")` again with `30599cc`.

**Comment by jethrokuan** [comment] 2020-06-09 05:24
@isolet when was the last you upgraded (prev hash)?

If you run `(org-roam-db-build-cache t)`, and don't see it anymore, then it's probably from some previous database incompatibilities.

**Comment by isolet** [comment] 2020-06-09 05:34
@jethrokuan 
I just upgraded to the latest master `30599cc` this morning. My org directory looks like

```
org
├── bibliography
│   ├── references.bib
│   ├── optimization.bib
│   ├── ...
│   └── default_refs.bib -> references.bib
├── notes
│   ├── some_notes.org
│   ├── some_notes2.org
... 
```

The issue comes from that there's a symbolic link `default_refs.bib` to `references.bib` in `bibliography`.

Deleting the database does nothing help while delete the symbolic link does.
